global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: dashboard
    static_configs:
      - targets: ["dashboard:8000"]
    metrics_path: /metrics

  - job_name: interactive_bot
    static_configs:
      - targets: ["interactive-bot:9101"]
    metrics_path: /metrics
